% ex03_options_lyap_integral.m
% Compare Lyapunov-based and numerical-integration Gramian computations.

clear; clc;

A = [ ...
    -0.6,  0.2,  0.0,  0.0; ...
     0.0, -0.9,  0.3,  0.0; ...
     0.1,  0.0,  0.2,  0.4; ...
     0.0,  0.0,  0.1,  0.7];
T = 2.0;

[pVLyap, pALyap, infoVLyap, infoALyap] = bothcs( ...
    A, T, Method="lyap", UseScaling=false);

[pVIntegral, pAIntegral, infoVIntegral, infoAIntegral] = bothcs( ...
    A, T, Method="integral", Steps=80, UseScaling=false);

disp("VCS weights:");
disp(table(pVLyap, pVIntegral, pVIntegral - pVLyap, ...
    'VariableNames', ["Lyap", "Integral", "Difference"]));

disp("AECS weights:");
disp(table(pALyap, pAIntegral, pAIntegral - pALyap, ...
    'VariableNames', ["Lyap", "Integral", "Difference"]));

disp("Solver iterations:");
iterations = table( ...
    ["VCS lyap"; "VCS integral"; "AECS lyap"; "AECS integral"], ...
    [infoVLyap.Iterations; infoVIntegral.Iterations; infoALyap.Iterations; infoAIntegral.Iterations], ...
    [infoVLyap.Converged; infoVIntegral.Converged; infoALyap.Converged; infoAIntegral.Converged], ...
    'VariableNames', ["Case", "Iterations", "Converged"]);
disp(iterations);
